### PR TITLE
Iss4

### PR DESCRIPTION
**Pull request by pbutti**
Added plots to check the hit smearing behaviour
Updates to python for the new naming scheme
Fixed underscore issue in the name of the library
Added analysis routines to the module

### CODE REVIEW

**Comment by pbutti** [comment]
Requested plots. Top row tagger hits, bottom row recoil
[TaggerAndRecoilResiduals.pdf](https://github.com/LDMX-Software/Tracking/files/7462703/TaggerAndRecoilResiduals.pdf)

**Comment by omar-moreno** [comment]
Analysis doesn't belong here. I would drop it in either the DQM or in the analysis  repo. 

Also, the cmake stuff has been fixed on another branch.

**Comment by pbutti** [comment]
Hi Omar,

I will re-work the analysis locations later on. I find it much easier to just compile this module for my own crosschecks instead of having to compile multiple modules to get the same plots.

**Comment by pbutti** [comment]
Fixed cmake conflict

**Comment by omar-moreno** [comment]
OK, Let's leave this unmerged until the analysis is moved elsewhere. You can use this as your analysis branch. I'll cherry pick the addition of the python modules.

**Comment by pbutti** [comment]
I think it's just me and you using this module at the moment. Blocking the PR (or cherry-picking) will make things more complicated just for us. Why not going ahead, get the analysis module in, and when things are more mature, we move it to DQM or ldmx-analysis or whatever you prefer =)

**Comment by omar-moreno** [comment]
I rather take care of things like this now than wait for later. These are
the types of things that, when put off for too long, make a mess of the
project.

The DQM module is built by ldmx-sw so there would be no need to build a
seperate module then. Also, this would allow us to easily add it to the
production chain. I can provide an example of how to run from the DQM if
needed.

**Comment by pbutti** [comment]
The removal of Analysis will be solved when iss10 will get merged. 
Are all the relevant parts of this PR included already?

**Pull request closed without merging**
